### ISSUE TITLE
issue in the code.

### ISSUE THREAD

**Issue by SagarRaiyani** [deib-polimi/PingPong#1]
Hello,

I have test this code but many error in this code please  give me a new code.

![capture](https://cloud.githubusercontent.com/assets/5584295/13314497/878131dc-dbcb-11e5-98ee-a32bd3c7fdfc.PNG)
![capture1](https://cloud.githubusercontent.com/assets/5584295/13314498/87859330-dbcb-11e5-8bc3-991a935203c9.PNG)
![capture3](https://cloud.githubusercontent.com/assets/5584295/13314495/877a44d0-dbcb-11e5-80d6-5917f4af5632.PNG)
![capture4](https://cloud.githubusercontent.com/assets/5584295/13314496/87810b26-dbcb-11e5-9171-fdceea6eb191.PNG)

**Comment by Ks89** [comment]
Hi.
Thank you for your interest in this project.

You should install Project Lombok plugin in Android Studio, because I created all getters and setters using Lombok.

Read the instruction at the end of this webpage https://projectlombok.org/setup/android.html
